# CI Workflow for artagon-parent
# Runs on PRs and pushes to main/develop branches

name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    uses: artagon/artagon-common/.github/workflows/java-build.yml@main
    with:
      java-version: '25'
      run-tests: true
      run-integration-tests: false

  security-scan:
    name: Security Scan
    needs: build
    uses: artagon/artagon-common/.github/workflows/security-scan.yml@main
    with:
      run-dependency-check: true
      run-ossindex-audit: true
      run-trivy-scan: true
      fail-on-severity: 'HIGH'
